setup:
    sudo apt install -y gpiod
    npm ci --omit=dev
    sudo cp planktoscope-org.backend.service /etc/systemd/system/
    sudo cp polkit.js /etc/polkit-1/rules.d/planktoscope.rules
    sudo systemctl reenable planktoscope-org.backend.service
    sudo systemctl restart planktoscope-org.backend.service
    sudo mkdir -p /data/tmp
    sudo chown -R pi:pi /data/tmp

setup-dev:
    npm install --include=dev

test:
    node --test

dev:
    -sudo systemctl stop planktoscope-org.backend
    node --watch src/service.js
