setup:
    just --justfile ../../justfile           install-node
    npm ci --omit=dev
    npm --prefix ../../lib ci --omit=dev
    npm --prefix ../rauc ci --omit=dev
    npm --prefix ../image ci --omit=dev
