setup:
    npm ci --omit=dev
    sudo cp mount-firmware.service /etc/systemd/system/
    sudo systemctl reenable mount-firmware.service
    sudo systemctl restart mount-firmware.service

setup-dev:
    npm install --include=dev

format:
    npx eslint --fix .

test:
    npx eslint .
    sudo cloud-init schema -c user-data.yaml --annotate
    validator user-data.yaml
    validator autoboot.ini
    validator cloud-init-local-override.ini
