# https://rauc.readthedocs.io/en/latest/reference.html#system-section
[system]
compatible=rauc-demo-x86
bootloader=custom
mountprefix=/mnt/rauc
bundle-formats=-plain
data-directory=/home/pi/data/rauc

# https://rauc.readthedocs.io/en/latest/using.html#system-based-customization-handlers
[handlers]
# https://rauc.readthedocs.io/en/latest/integration.html#custom
bootloader-custom-backend=./custom-bootloader-script
# https://rauc.readthedocs.io/en/latest/reference.html#handlers-section
# TODO
# system-info=/usr/lib/raspberrypi-firmware-rauc-bootloader-backend/system-info

# https://rauc.readthedocs.io/en/latest/reference.html#keyring-section
[keyring]
path=demo.cert.pem

# https://rauc.readthedocs.io/en/latest/reference.html#slot-slot-class-idx-sections
[slot.firmware.0]
device=/dev/nvme0n1p2
type=vfat
bootname=A

[slot.firmware.1]
device=/dev/nvme0n1p3
type=vfat
bootname=B

[slot.root.0]
parent=firmware.0
device=/dev/nvme0n1p4
type=ext4

[slot.root.1]
parent=firmware.1
device=/dev/nvme0n1p5
type=ext4
