[system]
compatible=rauc-demo-x86
bootloader=custom
mountprefix=/mnt/rauc
bundle-formats=-plain
data-directory=/home/pi/data/rauc

[handlers]
bootloader-custom-backend=custom-bootloader-script.js

[keyring]
path=demo.cert.pem

[slot.bootfs.0]
device=/dev/nvme0n1p2
type=vfat
bootname=A

[slot.bootfs.1]
device=/dev/nvme0n1p3
type=vfat
bootname=B

[slot.rootfs.0]
parent=bootfs.0
device=/dev/nvme0n1p4
type=ext4

[slot.rootfs.1]
parent=bootfs.1
device=/dev/nvme0n1p5
type=ext4
