setup:
    sudo ./setup_h264_sysctl.sh
    wget https://github.com/bluenviron/mediamtx/releases/download/v1.18.1/mediamtx_v1.18.1_linux_arm64.tar.gz -P /tmp
    wget https://raw.githubusercontent.com/bluenviron/mediamtx/refs/tags/v1.18.1/internal/servers/webrtc/reader.js -O /opt/PlanktoScope/frontend/src/pages/preview/reader.js
    cd /tmp && tar -xf /tmp/mediamtx_v1.18.1_linux_arm64.tar.gz
    -sudo systemctl stop mediamtx
    sudo cp /tmp/mediamtx /usr/local/bin/mediamtx
    sudo cp mediamtx.service /etc/systemd/system/
    sudo cp mediamtx.yaml /etc/mediamtx.yaml
    node ../../lib/mediamtx.js
    sudo systemctl reenable mediamtx
    sudo systemctl restart mediamtx

test:
    validator mediamtx.yaml

dev:
    -sudo systemctl stop mediamtx
    mediamtx /etc/mediamtx.yaml
