setup:
    sudo npm list -g node-red@v5.0.0-beta.4 || sudo npm install -g node-red@v5.0.0-beta.4
    npm ci --omit=dev
    sudo cp nodered.service /etc/systemd/system/
    sudo mkdir -p /etc/systemd/system/nodered.service.d
    sudo cp 30-override.conf /etc/systemd/system/nodered.service.d/
    sudo systemctl reenable nodered
    sudo systemctl restart nodered
    rm -rf /home/pi/.node-red

setup-dev:
    npm install --include=dev
    cd projects/dashboard && git remote set-url origin git@github.com:fairscope/dashboard.git
    cd projects/dashboard && git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    cd projects/dashboard && git fetch origin

dev:
    -sudo systemctl stop nodered
    node --watch-path /opt/PlanktoScope/node-red/nodes/ /usr/local/bin/node-red --settings /opt/PlanktoScope/node-red/settings.cjs

test:
    validator projects/dashboard/flows.json
    npx eslint .
    cd nodes && node --test

# Too many errors for now
# cd node-red && npx nrlint projects/dashboard/flows.json
