setup:
    # node-red projects needs git
    sudo apt install -y git
    sudo npm list -g node-red@v5.0.0 || sudo npm install -g node-red@v5.0.0
    npm ci --omit=dev
    mkdir -p context/global/
    cp global.json context/global/global.json
    sudo cp nodered.service /etc/systemd/system/
    sudo systemctl reenable nodered
    sudo systemctl restart nodered
    rm -rf /home/pi/.node-red

setup-dev:
    npm install --include=dev

dev:
    -sudo systemctl stop nodered
    node --watch-path /opt/PlanktoScope/node-red/nodes/ /usr/local/bin/node-red --settings /opt/PlanktoScope/node-red/settings.cjs

test:
    validator projects/dashboard/flows.json
    validator global.json
    npx eslint .
    cd nodes && node --test

# Too many errors for now
# cd node-red && npx nrlint projects/dashboard/flows.json
