setup:
    sudo apt install -y caddy
    sudo cp Caddyfile /etc/caddy/
    sudo systemctl reenable caddy
    sudo systemctl restart caddy
    chmod o+x /home/pi

format:
    caddy fmt --overwrite Caddyfile

test:
    caddy validate Caddyfile
