# https://rauc.readthedocs.io/en/latest/reference.html#manifest

[update]
compatible=PlanktoScope,rev1
version=X

[bundle]
format=verity

[image.FIRMWARE]
filename=FIRMWARE.vfat.img
type=vfat

[image.ROOT]
filename=ROOT.ext4.img
type=ext4
